name: fonctionnalite_lister_pokemons
description: Liste l&#x27;ensemble des Pokémons
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.8.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:

